
//---GENERAL
export const UPDATE_CONFIGS = 'UPDATE_CONFIGS';
export const LOAD_LOCAL_STORAGE_DATA = 'LOAD_LOCAL_STORAGE_DATA';
export const UPDATE_CUSTOM_USER_CONFIGS = 'UPDATE_CUSTOM_USER_CONFIGS';
export const SET_DEFAULT_CONFIGS = 'SET_DEFAULT_CONFIGS';
export const UPDATE_USER_COMPONENT_DATA = 'UPDATE_USER_COMPONENT_DATA';
export const SAVE_LOCAL_STORAGE_DATA = 'SAVE_LOCAL_STORAGE_DATA';

export const UPDATE_LOADER_STATE = 'UPDATE_LOADER_STATE';
export const SET_GLOBAL_SNOTIFY_DATA = 'SET_GLOBAL_SNOTIFY_DATA';

//---MODULES
//---Weather
export const GET_OWP_DATA = 'GET_OWP_DATA';




