
//---GENERAL
export const UPDATE_LOADER_STATE = 'UPDATE_LOADER_STATE';

export const SET_GLOBAL_SNOTIFY_DATA = 'SET_GLOBAL_SNOTIFY_DATA';

export const UPDATE_SITE_DATA = 'UPDATE_SITE_DATA';
export const GET_SITE_DATA = 'GET_SITE_DATA';

export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const USER_LOGOUT = 'USER_LOGOUT';

//---MODULES
//---Home
export const HOME_CONTENT = 'HOME_CONTENT';
export const GET_HOME_CONTENT = 'GET_HOME_CONTENT';

export const HOME_POPUP_STATUS = 'HOME_POPUP_STATUS';

//#todo del this all
export const SEARCH_PROPERTY_REQUEST = 'SEARCH_PROPERTY_REQUEST'
export const SEARCH_ADDITIONAL_DATA = 'SEARCH_ADDITIONAL_DATA'

export const CHECK_SUPPORT_PROPERTY = 'CHECK_SUPPORT_PROPERTY'
export const ANALYSIS_REQUEST = 'ANALYSIS_REQUEST'

export const REPORT_REQUEST = 'REPORT_REQUEST'

